# Generated by Django 6.0.1 on 2026-02-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
