# Generated by Django 6.0.1 on 2026-02-25 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='doctor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='api.doctor'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Rejected', 'Rejected')], default='Upcoming', max_length=20),
        ),
    ]
