# Generated by Django 6.0.1 on 2026-02-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_doctor_userprofile_is_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='shift',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], default='Morning', max_length=20),
        ),
    ]
