# Generated by Django 6.0.1 on 2026-02-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_medicalrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Accepted', 'Accepted'), ('Booked', 'Booked'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Rejected', 'Rejected')], default='Upcoming', max_length=20),
        ),
    ]
